export const LANDMARK_KIND_IDS = [
  "lattice-spire",
  "pagoda",
  "torii",
  "capsule",
  "clock-spire",
  "sail",
  "twist",
  "tri-needle",
  "gold-frame",
  "torus-museum",
  "pyramid",
  "sphinx",
  "pylon-gate",
  "obelisk",
  "statue",
  "gothic-spire",
  "dome",
  "mill",
  "chalet",
  "cable-pylon",
  "lighthouse",
  "ferris",
  "bridge-tower",
  "art-deco",
  "copper-steps",
  "neon-drum",
  "sugarloaf",
  "cristo",
  "portico",
  "ziggurat",
  "shard",
  "gherkin",
  "walkie-talkie",
  "glass-slab",
  "stepped-tower",
  "needle-spire",
] as const;

export type LandmarkKindId = (typeof LANDMARK_KIND_IDS)[number];

export interface CircuitLandmarkDef {
  name: string;
  kind: LandmarkKindId;
  color: string;
  accent: string;
  height: number;
}

type Entry = [string, LandmarkKindId, number];

function pack(
  entries: Entry[],
  palettes: Array<[string, string]>,
): CircuitLandmarkDef[] {
  return entries.map(([name, kind, height], i) => ({
    name,
    kind,
    color: palettes[i % palettes.length][0],
    accent: palettes[i % palettes.length][1],
    height,
  }));
}

const LONDON_PAL: Array<[string, string]> = [
  ["#8a7860", "#d4c4a8"],
  ["#c8d4e0", "#f0f8ff"],
  ["#6a8498", "#c8dce8"],
  ["#a89070", "#e8d8b8"],
  ["#d5dce4", "#9eacb8"],
  ["#b8a890", "#e8dcc8"],
];
const DUBAI_PAL: Array<[string, string]> = [
  ["#b8c8d6", "#d8e8f4"],
  ["#c9a84a", "#f4e0a0"],
  ["#1a2430", "#e8f4ff"],
  ["#6a9ab0", "#c8dce8"],
  ["#d8e4ee", "#b89840"],
];
const EGYPT_PAL: Array<[string, string]> = [
  ["#c4a06a", "#e8d0a0"],
  ["#9a7850", "#c8a878"],
  ["#c8c0b0", "#c9a84a"],
  ["#a88858", "#e0c888"],
];
const NYC_PAL: Array<[string, string]> = [
  ["#b8b4a8", "#d8d4c8"],
  ["#98a0a8", "#d4c080"],
  ["#4a8a72", "#c9a84a"],
  ["#e8eef4", "#f8fcff"],
  ["#c8ccd0", "#8a9098"],
];
const TOKYO_PAL: Array<[string, string]> = [
  ["#c8102e", "#f4f4f1"],
  ["#4a5860", "#88a0a8"],
  ["#ff3388", "#f0f0f0"],
  ["#68a0c8", "#d0ecff"],
  ["#2a3438", "#e8f0f4"],
];
const ALPS_PAL: Array<[string, string]> = [
  ["#8a6848", "#564235"],
  ["#7a8898", "#c8dce8"],
  ["#a88868", "#604838"],
  ["#c8d8e4", "#f4fbff"],
];
const RIO_PAL: Array<[string, string]> = [
  ["#a8b0a0", "#e8ece4"],
  ["#f0ece4", "#c9a84a"],
  ["#88b8c8", "#e8f8ff"],
  ["#4a6848", "#c8e0a0"],
  ["#e8e4dc", "#c9a227"],
];

/** 60 Westminster / Whitehall landmarks — real + skyline cues */
const WESTMINSTER = pack(
  [
    ["Elizabeth Tower", "clock-spire", 96],
    ["Palace of Westminster", "gothic-spire", 72],
    ["Westminster Abbey", "gothic-spire", 68],
    ["Victoria Tower", "gothic-spire", 98],
    ["Big Ben Lantern", "clock-spire", 88],
    ["MI6 Building", "stepped-tower", 52],
    ["Millbank Tower", "capsule", 118],
    ["Foreign Office", "portico", 48],
    ["Treasury Building", "portico", 44],
    ["Banqueting House", "portico", 36],
    ["Horse Guards", "portico", 32],
    ["Admiralty Arch", "pylon-gate", 40],
    ["Scotland Yard", "neon-drum", 46],
    ["Portcullis House", "copper-steps", 42],
    ["Churchill War Rooms", "ziggurat", 28],
    ["Central Hall Westminster", "dome", 58],
    ["St John's Smith Square", "dome", 40],
    ["Lambeth Palace", "gothic-spire", 38],
    ["County Hall", "portico", 48],
    ["London Eye", "ferris", 135],
    ["Westminster Bridge", "bridge-tower", 36],
    ["Cleopatra's Needle", "obelisk", 28],
    ["Boudica Statue", "statue", 24],
    ["Victoria Embankment", "lighthouse", 22],
    ["Shell Centre", "glass-slab", 86],
    ["St Thomas' Hospital", "glass-slab", 64],
    ["Park Plaza Westminster", "glass-slab", 54],
    ["Riverbank House", "glass-slab", 58],
    ["Ministry of Defence", "portico", 50],
    ["Downing Street Gate", "pylon-gate", 20],
    ["Jewel Tower", "gothic-spire", 26],
    ["St Margaret's Church", "gothic-spire", 34],
    ["Methodist Central Hall", "dome", 52],
    ["Queen Elizabeth II Centre", "glass-slab", 40],
    ["Channel 4 HQ", "copper-steps", 44],
    ["Tate Britain", "portico", 36],
    ["Vauxhall Bridge", "bridge-tower", 32],
    ["St George Wharf Tower", "needle-spire", 150],
    ["US Embassy Nine Elms", "glass-slab", 72],
    ["Battersea Power Station", "chimney" as never, 68],
    ["New Covent Garden Market", "mill", 28],
    ["Albert Embankment Light", "lighthouse", 42],
    ["Thames House", "glass-slab", 48],
    ["Deanery Lodge", "chalet", 26],
    ["Abbey Chapter House", "gothic-spire", 30],
    ["Parliament Square Obelisk", "obelisk", 22],
    ["Whitehall Cenotaph", "obelisk", 18],
    ["Citadel Admiralty", "ziggurat", 34],
    ["Dover House", "portico", 30],
    ["Gwydyr House", "portico", 28],
    ["Richmond House", "glass-slab", 46],
    ["Norman Shaw Buildings", "gothic-spire", 42],
    ["Bridge Street Towers", "bridge-tower", 38],
    ["Abingdon Street Gardens", "statue", 16],
    ["Smith Square Spire", "gothic-spire", 36],
    ["Millbank Estate", "copper-steps", 40],
    ["Thames Path Beacon", "lighthouse", 24],
    ["Vauxhall Cross", "stepped-tower", 50],
    ["Riverwalk Tower", "glass-slab", 70],
    ["Westminster Pier Light", "lighthouse", 20],
  ].map((e) => {
    // Fix Battersea — no chimney kind; use copper-steps
    if (e[0] === "Battersea Power Station") return ["Battersea Power Station", "copper-steps", 68] as Entry;
    return e as Entry;
  }),
  LONDON_PAL,
);

const EMBANKMENT = pack(
  [
    ["Somerset House", "portico", 48],
    ["Savoy Hotel", "art-deco", 62],
    ["Shell Mex House", "clock-spire", 78],
    ["Oxo Tower", "art-deco", 82],
    ["Tate Modern", "neon-drum", 70],
    ["The Shard", "shard", 160],
    ["City Hall", "capsule", 55],
    ["Shakespeare's Globe", "torus-museum", 34],
    ["Temple Church", "gothic-spire", 36],
    ["Waterloo Station", "glass-slab", 48],
    ["London Eye South", "ferris", 135],
    ["County Hall North", "portico", 46],
    ["National Theatre", "copper-steps", 52],
    ["Royal Festival Hall", "neon-drum", 44],
    ["Hungerford Bridge", "bridge-tower", 40],
    ["Blackfriars Bridge", "bridge-tower", 42],
    ["St Paul's Cathedral", "dome", 110],
    ["Unilever House", "portico", 54],
    ["Bankside Power Station", "copper-steps", 68],
    ["Millennium Bridge", "bridge-tower", 28],
    ["Southwark Cathedral", "gothic-spire", 50],
    ["The Gherkin Vista", "gherkin", 120],
    ["Walkie Talkie Vista", "walkie-talkie", 100],
    ["Lloyd's Building", "gold-frame", 88],
    ["Tower Bridge Vista", "bridge-tower", 65],
    ["Tower of London Vista", "gothic-spire", 40],
    ["Monument to Fire", "column" as never, 62],
    ["Cleopatra Needle Embankment", "obelisk", 28],
    ["Lion Embankment", "statue", 20],
    ["Festival Pier Light", "lighthouse", 24],
    ["ITV Studios", "glass-slab", 46],
    ["London Weekend Television", "glass-slab", 42],
    ["Sea Containers House", "art-deco", 58],
    ["Coin Street", "copper-steps", 36],
    ["Gabriel's Wharf", "mill", 28],
    ["Doggett Coat Arms", "chalet", 22],
    ["Middle Temple Hall", "gothic-spire", 32],
    ["Inner Temple", "portico", 30],
    ["Royal Courts of Justice", "gothic-spire", 72],
    ["Fleet Street Spire", "gothic-spire", 54],
    ["St Bride's Church", "gothic-spire", 68],
    ["Ludgate Hill", "dome", 48],
    ["One Blackfriars", "capsule", 110],
    ["Neo Bankside", "glass-slab", 64],
    ["The Sharp", "shard", 90],
    ["South Bank Centre", "copper-steps", 40],
    ["Hayward Gallery", "ziggurat", 34],
    ["Queen Elizabeth Hall", "neon-drum", 32],
    ["BFI Southbank", "glass-slab", 28],
    ["Jubilee Gardens Light", "lighthouse", 22],
    ["London Aquarium", "glass-slab", 36],
    ["Florence Nightingale Statue", "statue", 18],
    ["Boadicea Embankment", "statue", 22],
    ["Cleopatra Obelisk South", "obelisk", 26],
    ["Temple Pier", "lighthouse", 20],
    ["Waterloo Bridge", "bridge-tower", 38],
    ["Somerset House Courtyard", "portico", 40],
    ["King's Reach Tower", "needle-spire", 96],
    ["South Bank Tower", "glass-slab", 100],
    ["One Tower Bridge", "glass-slab", 72],
  ].map((e) => {
    if (e[0] === "Monument to Fire") return ["The Monument", "obelisk", 62] as Entry;
    return e as Entry;
  }),
  LONDON_PAL,
);

const CANARY = pack(
  [
    ["One Canada Square", "art-deco", 235],
    ["HSBC Tower", "capsule", 200],
    ["Citigroup Centre", "glass-slab", 200],
    ["One Churchill Place", "glass-slab", 156],
    ["25 Canada Square", "glass-slab", 200],
    ["40 Bank Street", "glass-slab", 153],
    ["10 Upper Bank Street", "glass-slab", 151],
    ["Newfoundland", "twist", 220],
    ["Landmark Pinnacle", "needle-spire", 233],
    ["Wardian London", "glass-slab", 187],
    ["Baltimore Tower", "glass-slab", 150],
    ["Pan Peninsula", "capsule", 147],
    ["Harbour Exchange", "glass-slab", 80],
    ["One Canada Crown", "pyramid", 24],
    ["Cabot Square", "portico", 36],
    ["West India Quay", "mill", 40],
    ["Museum of London Docklands", "copper-steps", 32],
    ["Canary Riverside", "glass-slab", 70],
    ["Billingsgate Market", "portico", 34],
    ["Heron Quays", "glass-slab", 90],
    ["South Quay Plaza", "needle-spire", 215],
    ["One Park Drive", "capsule", 160],
    ["Novotel Canary Wharf", "glass-slab", 68],
    ["Crossrail Place", "torus-museum", 40],
    ["Jubilee Line Canopy", "sail", 28],
    ["DLR Poplar", "cable-pylon", 36],
    ["Blackwall Yard", "lighthouse", 30],
    ["Isle of Dogs Obelisk", "obelisk", 26],
    ["Dockmaster House", "chalet", 22],
    ["Westferry Circus", "portico", 28],
    ["Bank Street Gate", "pylon-gate", 24],
    ["Morgan Stanley Building", "glass-slab", 110],
    ["Barclays HQ", "glass-slab", 120],
    ["JP Morgan Canary", "glass-slab", 130],
    ["Clifford Chance", "glass-slab", 100],
    ["KPMG Canary", "glass-slab", 95],
    ["State Street", "glass-slab", 88],
    ["20 Cabot Square", "glass-slab", 92],
    ["1 West India Quay", "glass-slab", 74],
    ["Canary Wharf Tube", "neon-drum", 32],
    ["Wood Wharf", "glass-slab", 140],
    ["Quay House", "copper-steps", 48],
    ["East Wintergarden", "gold-frame", 36],
    ["Waitrose Canopy", "sail", 22],
    ["Reuters Plaza", "statue", 18],
    ["Canada Square Park", "obelisk", 20],
    ["Middle Dock Bridge", "bridge-tower", 28],
    ["North Dock Light", "lighthouse", 24],
    ["South Dock Crane", "cable-pylon", 42],
    ["Millwall Dock", "mill", 30],
    ["Mudchute Farm", "chalet", 20],
    ["Island Gardens", "lighthouse", 22],
    ["Greenwich View", "dome", 48],
    ["Pepper St Bridge", "bridge-tower", 26],
    ["Marsh Wall Tower", "needle-spire", 160],
    ["Dollar Bay", "capsule", 109],
    ["The Summit", "glass-slab", 82],
    ["Manhattan Loft Gardens", "stepped-tower", 143],
    ["Arena Tower", "glass-slab", 115],
    ["City Pride Pub", "chalet", 18],
  ],
  LONDON_PAL,
);

const EGYPT = pack(
  [
    ["Great Pyramid of Khufu", "pyramid", 146],
    ["Pyramid of Khafre", "pyramid", 136],
    ["Pyramid of Menkaure", "pyramid", 65],
    ["Great Sphinx of Giza", "sphinx", 28],
    ["Valley Temple", "pylon-gate", 22],
    ["Sphinx Temple", "pylon-gate", 20],
    ["Queens' Pyramids", "pyramid", 32],
    ["Solar Boat Museum", "torus-museum", 24],
    ["Khufu Ship House", "chalet", 18],
    ["Giza Plateau Gate", "pylon-gate", 26],
    ["Sound and Light Stage", "neon-drum", 20],
    ["Mena House Hotel", "chalet", 28],
    ["Grand Egyptian Museum", "glass-slab", 48],
    ["GEM Obelisk Court", "obelisk", 36],
    ["Pyramid of Djoser", "ziggurat", 60],
    ["Saqqara Step Court", "ziggurat", 40],
    ["Hatshepsut Obelisk", "obelisk", 44],
    ["Ramses Colossus", "statue", 26],
    ["Horus Figure", "statue", 22],
    ["Anubis Court", "statue", 18],
    ["Mosque of Muhammad Ali", "dome", 78],
    ["Citadel of Saladin", "gothic-spire", 62],
    ["Al-Azhar Mosque", "dome", 52],
    ["Khan el-Khalili Gate", "pylon-gate", 24],
    ["Cairo Tower Vista", "needle-spire", 187],
    ["Nile Bridge Tower", "bridge-tower", 40],
    ["Alexandria Lighthouse Tribute", "lighthouse", 52],
    ["Cleopatra Palace Court", "portico", 30],
    ["Temple of Karnak Gate", "pylon-gate", 36],
    ["Luxor Obelisk Replica", "obelisk", 40],
    ["Nile Felucca Mast", "sail", 28],
    ["Desert Mastaba", "ziggurat", 34],
    ["Workers Village", "chalet", 16],
    ["Plateau Cable Pylon", "cable-pylon", 48],
    ["Giza Tram Light", "lighthouse", 22],
    ["Camel Station", "mill", 18],
    ["Sphinx Avenue", "sphinx", 20],
    ["Pyramid Causeway", "copper-steps", 14],
    ["Eastern Cemetery", "obelisk", 24],
    ["Western Cemetery", "obelisk", 22],
    ["Khentkaus Monument", "ziggurat", 28],
    ["Bent Pyramid Vista", "pyramid", 70],
    ["Red Pyramid Vista", "pyramid", 72],
    ["Meidum Pyramid Vista", "pyramid", 58],
    ["Nile Corniche Hotel", "glass-slab", 46],
    ["Cairo Opera House", "dome", 42],
    ["Tahrir Square Obelisk", "obelisk", 30],
    ["Egyptian Museum Tahrir", "portico", 36],
    ["Qaitbay Citadel", "lighthouse", 40],
    ["Abu Simbel Tribute", "statue", 32],
    ["Philae Temple Gate", "pylon-gate", 28],
    ["Kom Ombo Court", "portico", 26],
    ["Edfu Pylon", "pylon-gate", 34],
    ["Dendera Dome", "dome", 30],
    ["Valley of Kings Gate", "pylon-gate", 24],
    ["Hatshepsut Temple", "portico", 38],
    ["Colossi of Memnon", "statue", 28],
    ["Desert Watchtower", "lighthouse", 36],
    ["Oasis Palm Lodge", "chalet", 20],
    ["Sahara Ridge Beacon", "obelisk", 26],
  ],
  EGYPT_PAL,
);

const DUBAI = pack(
  [
    ["Burj Khalifa", "tri-needle", 280],
    ["Burj Al Arab", "sail", 160],
    ["Address Downtown", "glass-slab", 150],
    ["Cayan Tower", "twist", 140],
    ["Dubai Frame", "gold-frame", 100],
    ["Museum of the Future", "torus-museum", 88],
    ["Ain Dubai", "ferris", 160],
    ["Emirates Towers", "needle-spire", 180],
    ["Rose Rayhaan", "needle-spire", 150],
    ["JW Marriott Marquis", "glass-slab", 130],
    ["Princess Tower", "capsule", 140],
    ["23 Marina", "glass-slab", 135],
    ["Elite Residence", "glass-slab", 132],
    ["The Index", "glass-slab", 120],
    ["Ocean Heights", "sail", 110],
    ["Marina 101", "needle-spire", 125],
    ["Damac Heights", "twist", 115],
    ["Ciel Tower", "capsule", 145],
    ["Dubai Marina Mall", "glass-slab", 40],
    ["JBR Beach Light", "lighthouse", 30],
    ["Palm Jumeirah Gate", "pylon-gate", 36],
    ["Atlantis The Palm", "dome", 60],
    ["The Pointe", "lighthouse", 28],
    ["Bluewaters Island", "ferris", 50],
    ["DIFC Gate", "gold-frame", 48],
    ["Gate Village", "glass-slab", 52],
    ["Emirates NBD", "glass-slab", 90],
    ["Dubai Mall Fountain", "obelisk", 24],
    ["Dubai Opera", "sail", 42],
    ["Souk Al Bahar", "chalet", 22],
    ["Old Town Palace", "portico", 34],
    ["Grand Mosque Dubai", "dome", 64],
    ["Jumeirah Mosque", "dome", 40],
    ["Zabeel Palace Gate", "pylon-gate", 32],
    ["Sheikh Zayed Road Spire", "needle-spire", 100],
    ["World Trade Centre Dubai", "art-deco", 80],
    ["Al Yaqoub Tower", "clock-spire", 110],
    ["HHHR Tower", "glass-slab", 95],
    ["Infinity Tower Marina", "twist", 105],
    ["Marina Gate", "pylon-gate", 30],
    ["Pier 7", "neon-drum", 26],
    ["Yacht Club Dubai", "sail", 28],
    ["Metro Marina Station", "cable-pylon", 36],
    ["Tram Pylon", "cable-pylon", 32],
    ["Jebel Ali Light", "lighthouse", 40],
    ["Desert Pyramid Hotel", "pyramid", 46],
    ["Falcon Monument", "statue", 24],
    ["Sheikh Statue Court", "statue", 22],
    ["Creek Tower Site", "needle-spire", 90],
    ["Dubai Creek Harbour", "glass-slab", 70],
    ["Ras Al Khor Lodge", "chalet", 18],
    ["Hatta Mountain Cone", "sugarloaf", 50],
    ["Al Fahidi Fort", "ziggurat", 28],
    ["Heritage Village", "chalet", 20],
    ["Gold Souk Gate", "pylon-gate", 22],
    ["Spice Souk Arch", "pylon-gate", 20],
    ["Abra Dock Light", "lighthouse", 16],
    ["Business Bay Bridge", "bridge-tower", 44],
    ["Water Canal Tower", "glass-slab", 85],
    ["ICD Brookfield", "glass-slab", 120],
  ],
  DUBAI_PAL,
);

const NYC = pack(
  [
    ["Empire State Building", "art-deco", 150],
    ["Chrysler Building", "art-deco", 140],
    ["One World Trade Center", "needle-spire", 200],
    ["Statue of Liberty", "statue", 90],
    ["Brooklyn Bridge", "bridge-tower", 78],
    ["Flatiron Building", "art-deco", 70],
    ["Woolworth Building", "gothic-spire", 100],
    ["St Patrick's Cathedral", "gothic-spire", 72],
    ["Grand Central Terminal", "portico", 48],
    ["New York Public Library", "portico", 40],
    ["MetLife Building", "glass-slab", 88],
    ["Seagram Building", "capsule", 96],
    ["Lever House", "glass-slab", 74],
    ["Hearst Tower", "twist", 120],
    ["30 Hudson Yards", "needle-spire", 160],
    ["The Edge", "glass-slab", 48],
    ["Vessel Hudson Yards", "gold-frame", 40],
    ["Guggenheim Museum", "torus-museum", 46],
    ["Met Museum", "portico", 42],
    ["UN Headquarters", "glass-slab", 80],
    ["Citigroup Center", "stepped-tower", 110],
    ["Bank of America Tower", "needle-spire", 130],
    ["432 Park Avenue", "capsule", 140],
    ["Central Park Tower", "needle-spire", 155],
    ["Steinway Tower", "needle-spire", 145],
    ["One Vanderbilt", "needle-spire", 135],
    ["Times Square Tower", "neon-drum", 56],
    ["Paramount Building", "art-deco", 64],
    ["Radio City Music Hall", "art-deco", 36],
    ["Rockefeller Center", "art-deco", 90],
    ["GE Building", "art-deco", 92],
    ["Washington Square Arch", "pylon-gate", 36],
    ["Cleopatra's Needle NYC", "obelisk", 30],
    ["Battery Park Light", "lighthouse", 24],
    ["Ellis Island", "dome", 40],
    ["Governors Island Fort", "ziggurat", 28],
    ["Brooklyn Heights Pier", "lighthouse", 22],
    ["Wonder Wheel Coney", "ferris", 64],
    ["High Line Pavilion", "copper-steps", 24],
    ["Whitney Museum", "copper-steps", 40],
    ["The Standard Hotel", "glass-slab", 52],
    ["Oculus WTC", "sail", 44],
    ["9/11 Memorial Pools", "obelisk", 18],
    ["Trinity Church", "gothic-spire", 54],
    ["Federal Hall", "portico", 32],
    ["New York Stock Exchange", "portico", 34],
    ["Charging Bull", "statue", 16],
    ["Fearless Girl", "statue", 14],
    ["Brooklyn Borough Hall", "dome", 38],
    ["Manhattan Bridge", "bridge-tower", 70],
    ["Williamsburg Bridge", "bridge-tower", 66],
    ["Queensboro Bridge", "bridge-tower", 68],
    ["Roosevelt Island Tram", "cable-pylon", 50],
    ["United Nations Obelisk", "obelisk", 26],
    ["Columbus Circle", "statue", 20],
    ["Lincoln Center", "portico", 36],
    ["Apollo Theater", "neon-drum", 28],
    ["Harlem Clock Tower", "clock-spire", 46],
    ["Yankee Stadium Light", "lighthouse", 40],
    ["Intrepid Museum", "sail", 32],
  ],
  NYC_PAL,
);

const TOKYO = pack(
  [
    ["Tokyo Tower", "lattice-spire", 120],
    ["Tokyo Skytree", "tri-needle", 180],
    ["Senso-ji Temple", "pagoda", 52],
    ["Senso-ji Gate", "torii", 28],
    ["Meiji Shrine Torii", "torii", 24],
    ["Mode Gakuen Cocoon", "capsule", 110],
    ["Mode Gakuen Spiral", "twist", 100],
    ["Tokyo Metropolitan Government", "gothic-spire", 140],
    ["NTT Docomo Yoyogi", "clock-spire", 96],
    ["Rainbow Bridge", "bridge-tower", 76],
    ["Tokyo Gate Bridge", "bridge-tower", 70],
    ["Asakusa Culture Center", "pagoda", 40],
    ["Nakagin Capsule Tower", "capsule", 54],
    ["Shibuya Scramble Sign", "neon-drum", 36],
    ["Shibuya 109", "neon-drum", 42],
    ["Hachiko Statue", "statue", 14],
    ["Takeshita Street Gate", "torii", 18],
    ["Harajuku Station", "glass-slab", 28],
    ["Omotesando Hills", "copper-steps", 40],
    ["Prada Aoyama", "gold-frame", 32],
    ["Roppongi Hills Mori", "glass-slab", 100],
    ["Tokyo Midtown", "glass-slab", 95],
    ["Azabudai Hills", "needle-spire", 130],
    ["Toranomon Hills", "glass-slab", 105],
    ["Tokyo Station Marunouchi", "dome", 46],
    ["Imperial Palace Gate", "pylon-gate", 30],
    ["Nijubashi Bridge", "bridge-tower", 22],
    ["Yasukuni Torii", "torii", 26],
    ["Ueno Park Obelisk", "obelisk", 28],
    ["Tokyo National Museum", "portico", 36],
    ["Skytree Town", "glass-slab", 48],
    ["Sumida Aquarium", "glass-slab", 32],
    ["Asahi Flame Building", "gold-frame", 44],
    ["Philippe Starck Flame", "sail", 40],
    ["Ginza Wako Clock", "clock-spire", 34],
    ["Kabukiza Theatre", "pagoda", 30],
    ["Tsukiji Outer Gate", "pylon-gate", 20],
    ["TeamLab Planets", "torus-museum", 28],
    ["Odaiba Statue of Liberty", "statue", 36],
    ["Fuji TV Building", "gold-frame", 50],
    ["Palette Town Cosmo Clock", "ferris", 70],
    ["Yokohama Marine Tower", "lighthouse", 58],
    ["Yokohama Landmark Tower", "needle-spire", 120],
    ["Mount Fuji Vista Cone", "sugarloaf", 80],
    ["Akihabara Crossroad", "neon-drum", 38],
    ["Electric Town Gate", "neon-drum", 26],
    ["Kanda Myojin", "pagoda", 32],
    ["Yamanote Pylon", "cable-pylon", 40],
    ["Shinkansen Shed", "glass-slab", 34],
    ["Tokyo Big Sight", "pyramid", 48],
    ["Odaiba Beach Light", "lighthouse", 24],
    ["Rainbow Town Pier", "lighthouse", 20],
    ["Zojo-ji Temple", "pagoda", 36],
    ["Tokyo Tower Foot Town", "chalet", 22],
    ["Roppongi Crossing", "neon-drum", 30],
    ["National Art Center", "sail", 36],
    ["Suntory Museum", "glass-slab", 28],
    ["Atago Shrine Stairs", "copper-steps", 24],
    ["Hamarikyu Gardens Gate", "torii", 18],
    ["Tsukudajima Lighthouse", "lighthouse", 22],
  ],
  TOKYO_PAL,
);

const ALPS = pack(
  [
    ["Matterhorn Peak", "sugarloaf", 90],
    ["Matterhorn Glacier Paradise", "glass-slab", 40],
    ["Gornergrat Kulm", "chalet", 36],
    ["Gornergrat Observatory", "dome", 28],
    ["Zermatt Parish Church", "gothic-spire", 42],
    ["Zermatt Clock Tower", "clock-spire", 34],
    ["Hörnlihütte", "chalet", 26],
    ["Monte Rosa Hut", "capsule", 30],
    ["Klein Matterhorn", "needle-spire", 70],
    ["Theodul Pass", "cable-pylon", 48],
    ["Matterhorn Express Pylon", "cable-pylon", 52],
    ["Sunnegga Station", "chalet", 24],
    ["Rothorn Summit", "sugarloaf", 60],
    ["Findeln Chapel", "gothic-spire", 22],
    ["Winkelmatten Chapel", "gothic-spire", 20],
    ["Zmutt Hamlet", "chalet", 18],
    ["Blatten Village", "chalet", 16],
    ["Furi Bridge", "bridge-tower", 28],
    ["Glacier Cable Car", "cable-pylon", 56],
    ["Ice Pavilion", "torus-museum", 24],
    ["Alpine Museum", "chalet", 22],
    ["Grand Hotel Zermatterhof", "portico", 32],
    ["Mont Cervin Palace", "art-deco", 36],
    ["Riffelalp Resort", "chalet", 28],
    ["Riffelberg Hotel", "chalet", 26],
    ["Kulmhotel Gornergrat", "chalet", 30],
    ["Matterhorn Museum", "glass-slab", 20],
    ["Bahnhof Zermatt", "glass-slab", 24],
    ["Gorner Gorge Bridge", "bridge-tower", 22],
    ["Triftbach Waterfall Mill", "mill", 18],
    ["Stellisee Reflection", "obelisk", 14],
    ["Grindjisee Lodge", "chalet", 16],
    ["Green Lake Hut", "chalet", 16],
    ["Schwarzsee Chapel", "gothic-spire", 20],
    ["Trockener Steg", "cable-pylon", 44],
    ["Testa Grigia", "chalet", 28],
    ["Breithorn Plateau", "sugarloaf", 50],
    ["Castor Peak", "sugarloaf", 48],
    ["Pollux Peak", "sugarloaf", 46],
    ["Lyskamm Ridge", "needle-spire", 55],
    ["Dufourspitze Vista", "needle-spire", 58],
    ["Alpine Ibex Statue", "statue", 14],
    ["Saint Bernard Monument", "statue", 16],
    ["Mountain Guide Statue", "statue", 15],
    ["Avalanche Barrier", "ziggurat", 20],
    ["Snow Fence Line", "cable-pylon", 18],
    ["Pass Road Light", "lighthouse", 22],
    ["Tunnel Portal", "pylon-gate", 24],
    ["Hydro Dam Wall", "copper-steps", 36],
    ["Valley Frame Lodge", "chalet", 20],
    ["Ski Jump Tower", "needle-spire", 40],
    ["Halfpipe Lights", "neon-drum", 18],
    ["Fondue Hut", "chalet", 14],
    ["Cheese Dairy", "mill", 16],
    ["Cow Bell Tower", "clock-spire", 18],
    ["Edelweiss Garden", "obelisk", 12],
    ["Summit Cross", "statue", 20],
    ["Glacier Crevasse Bridge", "bridge-tower", 26],
    ["Ice Cave Entrance", "pylon-gate", 18],
    ["Alpine Rescue Beacon", "lighthouse", 30],
  ],
  ALPS_PAL,
);

const RIO = pack(
  [
    ["Christ the Redeemer", "cristo", 92],
    ["Sugarloaf Mountain", "sugarloaf", 96],
    ["Corcovado Peak", "sugarloaf", 80],
    ["Pão de Açúcar Cable", "cable-pylon", 58],
    ["Bondinho Station", "chalet", 28],
    ["Copacabana Palace", "art-deco", 48],
    ["Copacabana Fort", "ziggurat", 32],
    ["Ipanema Beach Light", "lighthouse", 26],
    ["Arpoador Rock", "sugarloaf", 40],
    ["Dois Irmãos", "sugarloaf", 74],
    ["Pedra da Gávea", "sugarloaf", 70],
    ["Maracanã Stadium", "torus-museum", 55],
    ["Cathedral of Rio", "pyramid", 72],
    ["Candelária Church", "dome", 50],
    ["Theatro Municipal", "portico", 42],
    ["Arcos da Lapa", "bridge-tower", 38],
    ["Santa Teresa Tram", "cable-pylon", 30],
    ["Selarón Steps", "copper-steps", 24],
    ["Lapa Bonde", "mill", 22],
    ["Museum of Tomorrow", "sail", 40],
    ["MAR Museum", "glass-slab", 36],
    ["Niterói Contemporary Art", "torus-museum", 34],
    ["Rio-Niterói Bridge", "bridge-tower", 66],
    ["Sugarloaf Urca", "chalet", 24],
    ["Praia Vermelha", "lighthouse", 20],
    ["Flamengo Park Obelisk", "obelisk", 28],
    ["Monument to Estácio", "statue", 22],
    ["Santos Dumont Airport Tower", "lighthouse", 32],
    ["Avenida Atlântica", "art-deco", 40],
    ["Copacabana Sidewalk Wave", "neon-drum", 16],
    ["Ipanema Garota Statue", "statue", 14],
    ["Leblon Beach Post", "lighthouse", 18],
    ["Vidigal Favela Ridge", "ziggurat", 36],
    ["Rocinha Overlook", "chalet", 26],
    ["Tijuca Peak Cross", "statue", 30],
    ["Vista Chinesa", "pagoda", 28],
    ["Mesa do Imperador", "portico", 22],
    ["Botanical Garden Gate", "pylon-gate", 24],
    ["Jardim Botânico Palm", "obelisk", 20],
    ["São Conrado Fashion Mall", "glass-slab", 34],
    ["Barra Olympic Park", "sail", 38],
    ["Riocentro", "glass-slab", 30],
    ["City of Arts", "sail", 36],
    ["Pedra Bonita Ramp", "cable-pylon", 40],
    ["São Conrado Beach", "lighthouse", 20],
    ["Gavea Golf Club", "chalet", 18],
    ["Lagoa Rodrigo de Freitas", "torus-museum", 16],
    ["Cantagalo Tower", "needle-spire", 48],
    ["Cantareira Ridge", "sugarloaf", 44],
    ["Guanabara Bay Fort", "ziggurat", 30],
    ["Ilha Fiscal", "gothic-spire", 28],
    ["Municipal Market", "portico", 26],
    ["Cinelândia Obelisk", "obelisk", 24],
    ["Biblioteca Nacional", "portico", 36],
    ["Palácio Tiradentes", "portico", 32],
    ["Sambadrome", "neon-drum", 28],
    ["Marquês de Sapucaí", "copper-steps", 22],
    ["Praça Mauá Crane", "cable-pylon", 34],
    ["AquaRio", "glass-slab", 30],
    ["Boulevard Olímpico", "statue", 18],
  ],
  RIO_PAL,
);

export const CIRCUIT_LANDMARKS: Record<string, CircuitLandmarkDef[]> = {
  "westminster-sprint": WESTMINSTER,
  "embankment-run": EMBANKMENT,
  "canary-wharf-loop": CANARY,
  "egypt-pyramids": EGYPT,
  "dubai-marina-circuit": DUBAI,
  "new-york-harbor-circuit": NYC,
  "tokyo-drift-circuit": TOKYO,
  "alps-mountain-pass": ALPS,
  "rio-coast-circuit": RIO,
};

const BY_NAME = new Map<string, CircuitLandmarkDef>();
for (const list of Object.values(CIRCUIT_LANDMARKS)) {
  for (const item of list) BY_NAME.set(item.name.toLowerCase(), item);
}

export function circuitLandmarksFor(slug: string): CircuitLandmarkDef[] {
  const base = CIRCUIT_LANDMARKS[slug] ?? [];
  const target = 90;
  if (base.length >= target) return base;
  const kinds = LANDMARK_KIND_IDS.filter(
    (k) => !["ferris", "pyramid", "sphinx", "statue"].includes(k),
  );
  const palettes =
    slug.includes("dubai")
      ? DUBAI_PAL
      : slug.includes("egypt")
        ? EGYPT_PAL
        : slug.includes("york")
          ? NYC_PAL
          : slug.includes("tokyo")
            ? TOKYO_PAL
            : slug.includes("alps")
              ? ALPS_PAL
              : slug.includes("rio")
                ? RIO_PAL
                : LONDON_PAL;
  const extras: CircuitLandmarkDef[] = [];
  for (let i = base.length; i < target; i++) {
    const kind = kinds[i % kinds.length];
    const [color, accent] = palettes[i % palettes.length];
    extras.push({
      name: `${slug.split("-")[0]} Streetscape ${i + 1}`,
      kind,
      color,
      accent,
      height: 28 + ((i * 7) % 90),
    });
  }
  return [...base, ...extras];
}

export function circuitLandmarkByName(name?: string): CircuitLandmarkDef | null {
  if (!name) return null;
  return BY_NAME.get(name.toLowerCase()) ?? null;
}
