export const LANDMARK_KIND_IDS = [
  "lattice-spire",
  "pagoda",
  "torii",
  "capsule",
  "clock-spire",
  "sail",
  "twist",
  "tri-needle",
  "gold-frame",
  "torus-museum",
  "pyramid",
  "sphinx",
  "pylon-gate",
  "obelisk",
  "statue",
  "gothic-spire",
  "dome",
  "mill",
  "chalet",
  "cable-pylon",
  "lighthouse",
  "ferris",
  "bridge-tower",
  "art-deco",
  "copper-steps",
  "neon-drum",
  "sugarloaf",
  "cristo",
  "portico",
  "ziggurat",
] as const;

export type LandmarkKindId = (typeof LANDMARK_KIND_IDS)[number];

export interface CircuitLandmarkDef {
  name: string;
  kind: LandmarkKindId;
  color: string;
  accent: string;
  height: number;
}

function pack(
  names: string[],
  palettes: Array<[string, string]>,
  heights: number[],
): CircuitLandmarkDef[] {
  return names.slice(0, 30).map((name, i) => ({
    name,
    kind: LANDMARK_KIND_IDS[i],
    color: palettes[i % palettes.length][0],
    accent: palettes[i % palettes.length][1],
    height: heights[i % heights.length],
  }));
}

const LONDON_PAL: Array<[string, string]> = [
  ["#8a7860", "#d4c4a8"],
  ["#c8d4e0", "#f0f8ff"],
  ["#6a8498", "#c8dce8"],
  ["#a89070", "#e8d8b8"],
];
const DUBAI_PAL: Array<[string, string]> = [
  ["#b8c8d6", "#d8e8f4"],
  ["#c9a84a", "#f4e0a0"],
  ["#1a2430", "#e8f4ff"],
  ["#6a9ab0", "#c8dce8"],
];
const EGYPT_PAL: Array<[string, string]> = [
  ["#c4a06a", "#e8d0a0"],
  ["#9a7850", "#c8a878"],
  ["#c8c0b0", "#c9a84a"],
  ["#a88858", "#e0c888"],
];
const NYC_PAL: Array<[string, string]> = [
  ["#b8b4a8", "#d8d4c8"],
  ["#98a0a8", "#d4c080"],
  ["#4a8a72", "#c9a84a"],
  ["#e8eef4", "#f8fcff"],
];
const TOKYO_PAL: Array<[string, string]> = [
  ["#c8102e", "#f4f4f1"],
  ["#4a5860", "#88a0a8"],
  ["#ff3388", "#f0f0f0"],
  ["#68a0c8", "#d0ecff"],
];
const ALPS_PAL: Array<[string, string]> = [
  ["#8a6848", "#564235"],
  ["#7a8898", "#c8dce8"],
  ["#a88868", "#604838"],
  ["#c8d8e4", "#f4fbff"],
];
const RIO_PAL: Array<[string, string]> = [
  ["#a8b0a0", "#e8ece4"],
  ["#f0ece4", "#c9a84a"],
  ["#88b8c8", "#e8f8ff"],
  ["#4a6848", "#c8e0a0"],
];

const WESTMINSTER = pack(
  [
    "Foreign Office Court",
    "Big Ben Lantern",
    "Admiralty Gate",
    "Portcullis Capsule",
    "Elizabeth Tower Court",
    "Thames Sail House",
    "Millbank Twist",
    "MI6 Needle",
    "Parliament Frame",
    "Abbey Chapter",
    "Victoria Pyramid Court",
    "Sphinx Embankment",
    "Horse Guards Arch",
    "Cleopatra Court Needle",
    "Boudica Statue",
    "Westminster Spire",
    "Central Hall Dome",
    "Lambeth Mill",
    "Deanery Lodge",
    "Cable House Pylon",
    "Albert Embankment Light",
    "London Eye Court",
    "Westminster Bridge Tower",
    "Whitehall Deco",
    "Copper Treasury",
    "Scotland Yard Drum",
    "Vauxhall Cone",
    "Peace Statue Court",
    "Banqueting Portico",
    "Churchill Ziggurat",
  ],
  LONDON_PAL,
  [48, 92, 36, 70, 88, 64, 118, 140, 52, 44, 38, 22, 40, 28, 24, 96, 58, 32, 26, 74, 42, 80, 68, 90, 56, 62, 46, 34, 40, 30],
);

const EMBANKMENT = pack(
  [
    "Somerset Lantern",
    "Savoy Pagoda Court",
    "Hungerford Torii",
    "Festival Capsule",
    "Shell Mex Clock",
    "Oxo Sail",
    "Tate Twist",
    "Shard Vista Needle",
    "City Hall Frame",
    "Globe Ring",
    "Temple Pyramid",
    "Lion Embankment",
    "Waterloo Arch",
    "Needle of the Thames",
    "South Bank Statue",
    "St Paul's Vista Spire",
    "Unilever Dome",
    "Oxo Mill",
    "Bankside Lodge",
    "Hungerford Pylon",
    "County Hall Light",
    "Eye Wheel Court",
    "Blackfriars Tower",
    "Festival Deco",
    "Copper Wharf",
    "National Theatre Drum",
    "Southwark Cone",
    "Wharf Cristo Court",
    "Somerset Portico",
    "Tate Ziggurat",
  ],
  LONDON_PAL,
  [50, 62, 34, 52, 78, 82, 70, 160, 55, 34, 36, 20, 48, 32, 26, 110, 54, 30, 28, 72, 44, 86, 66, 88, 58, 52, 42, 36, 46, 32],
);

const CANARY = pack(
  [
    "Canada Square Lantern",
    "Cabot Pagoda",
    "West India Torii",
    "HSBC Capsule",
    "DLR Clock Court",
    "Newfoundland Sail",
    "Citi Twist",
    "Pinnacle Needle",
    "Wintergarden Frame",
    "East Winter Ring",
    "Quay Pyramid",
    "Dock Lion",
    "Billingsgate Arch",
    "Isle Obelisk",
    "Dockmaster Statue",
    "Barclays Spire",
    "Cabot Dome",
    "Dock Mill",
    "Heron Quay Lodge",
    "Jubilee Pylon",
    "South Quay Light",
    "Crossrail Wheel",
    "Bank Street Tower",
    "Morgan Deco",
    "Copper Wharf East",
    "Novotel Drum",
    "Wardian Cone",
    "Quay Cristo",
    "Circus Portico",
    "Canary Ziggurat",
  ],
  LONDON_PAL,
  [80, 54, 36, 96, 48, 88, 140, 180, 42, 32, 34, 18, 46, 40, 24, 120, 58, 28, 26, 90, 64, 70, 110, 92, 72, 68, 84, 38, 44, 36],
);

const EGYPT = pack(
  [
    "Khufu Beacon",
    "Karnak Pagoda Court",
    "Sphinx Torii Court",
    "GEM Capsule",
    "Cairo Clock",
    "Nile Sail House",
    "Khafre Twist",
    "Menkaure Needle",
    "Saladin Frame",
    "Solar Boat Ring",
    "Great Pyramid Court",
    "Great Sphinx",
    "Valley Gate",
    "Hatshepsut Obelisk",
    "Ramses Statue",
    "Mosque Spire",
    "Mena Dome",
    "Nile Mill",
    "Plateau Lodge",
    "Giza Cable Pylon",
    "Alexandria Light",
    "Sound Light Wheel",
    "Citadel Tower",
    "Art Deco Cairo",
    "Copper Mastaba",
    "Workers Drum",
    "Desert Cone",
    "Horus Figure",
    "Temple Portico",
    "Step Pyramid",
  ],
  EGYPT_PAL,
  [72, 40, 28, 48, 86, 54, 64, 90, 58, 22, 110, 28, 36, 44, 26, 78, 42, 24, 22, 70, 52, 46, 62, 48, 34, 30, 40, 32, 38, 56],
);

const DUBAI = pack(
  [
    "Burj Lantern Court",
    "Palm Pagoda",
    "Marina Torii",
    "Address Capsule",
    "DIFC Clock",
    "Burj Al Arab Sail",
    "Cayan Twist",
    "Khalifa Needle",
    "Dubai Frame Court",
    "Future Museum Ring",
    "Desert Pyramid Hotel",
    "Falcon Court",
    "Gate Village Arch",
    "Jumeirah Obelisk",
    "Sheikh Statue Court",
    "Rose Spire",
    "Grand Mosque Dome",
    "Creek Mill",
    "Desert Lodge",
    "Metro Pylon",
    "Jebel Light",
    "Ain Dubai Wheel",
    "Brookfield Tower",
    "Deco Marina",
    "Copper Creek",
    "Neon Drum Hotel",
    "Hatta Cone",
    "Falcon Cristo",
    "Palace Portico",
    "Zabeel Ziggurat",
  ],
  DUBAI_PAL,
  [90, 48, 36, 110, 70, 160, 140, 220, 100, 88, 46, 24, 52, 40, 28, 150, 64, 32, 26, 96, 58, 92, 130, 84, 72, 76, 50, 34, 44, 42],
);

const NYC = pack(
  [
    "Liberty Lantern",
    "Chinatown Pagoda",
    "Central Park Torii",
    "Seagram Capsule",
    "MetLife Clock",
    "Hudson Sail",
    "Hearst Twist",
    "One WTC Needle",
    "Brooklyn Frame",
    "Guggenheim Ring",
    "Met Pyramid Court",
    "NYPL Lions",
    "Washington Arch",
    "Cleopatra Needle NYC",
    "Liberty Statue Court",
    "Chrysler Spire",
    "St Patrick Dome",
    "Brooklyn Mill",
    "High Line Lodge",
    "Roosevelt Pylon",
    "Harbor Light",
    "Wonder Wheel",
    "Brooklyn Bridge Tower",
    "Empire Deco",
    "Copper Buildings",
    "Times Square Drum",
    "The Edge Cone",
    "Harbor Cristo",
    "Custom House Portico",
    "Ziggurat Midtown",
  ],
  NYC_PAL,
  [70, 42, 32, 96, 88, 74, 120, 200, 80, 46, 40, 22, 36, 30, 90, 170, 72, 28, 24, 86, 54, 64, 78, 150, 68, 56, 48, 38, 44, 40],
);

const TOKYO = pack(
  [
    "Tokyo Tower Court",
    "Asakusa Pagoda",
    "Meiji Torii",
    "Cocoon Capsule",
    "Docomo Clock",
    "Rainbow Sail",
    "Mode Gakuen Twist",
    "Skytree Needle",
    "Gate Frame Aoyama",
    "TeamLab Ring",
    "Edo Pyramid Court",
    "Komainu Court",
    "Senso-ji Gate",
    "Ueno Obelisk",
    "Hachiko Statue",
    "Tocho Spire",
    "Senso Dome",
    "Sumida Mill",
    "Yanaka Lodge",
    "Yamanote Pylon",
    "Yokohama Light",
    "Cosmo Wheel",
    "Rainbow Bridge Tower",
    "Ginza Deco",
    "Copper Nakagin",
    "Shibuya Drum",
    "Fuji Vista Cone",
    "Peace Figure",
    "Imperial Portico",
    "Edo Ziggurat",
  ],
  TOKYO_PAL,
  [120, 52, 28, 110, 96, 64, 100, 180, 48, 36, 34, 18, 40, 32, 22, 140, 46, 26, 24, 82, 58, 70, 76, 88, 54, 62, 50, 30, 42, 38],
);

const ALPS = pack(
  [
    "Matterhorn Beacon",
    "Alpine Pagoda Court",
    "Chapel Torii",
    "Glacier Capsule",
    "Zermatt Clock",
    "Gornergrat Sail",
    "Horn Twist",
    "Peak Needle",
    "Valley Frame",
    "Ice Ring",
    "Snow Pyramid",
    "Ibex Court",
    "Furi Gate",
    "Findeln Obelisk",
    "Guide Statue",
    "Parish Spire",
    "Church Dome",
    "Water Mill",
    "Hörnli Lodge",
    "Cable Car Pylon",
    "Pass Light",
    "Ferris Alp",
    "Bridge Tower Pass",
    "Grand Hotel Deco",
    "Copper Chalet",
    "Station Drum",
    "Klein Cone",
    "Summit Figure",
    "Kurhaus Portico",
    "Moraine Ziggurat",
  ],
  ALPS_PAL,
  [56, 34, 24, 48, 40, 52, 64, 90, 36, 28, 44, 16, 32, 30, 20, 62, 38, 22, 26, 80, 42, 36, 54, 46, 28, 34, 70, 24, 32, 30],
);

const RIO = pack(
  [
    "Corcovado Lantern",
    "Santa Teresa Pagoda",
    "Ipanema Torii",
    "Italia Capsule",
    "Copacabana Clock",
    "Tomorrow Sail",
    "Dois Irmaos Twist",
    "Sugarloaf Needle",
    "Lapa Frame",
    "Tomorrow Ring",
    "Maracana Pyramid",
    "Jaguar Court",
    "Arcos da Lapa",
    "Gloria Obelisk",
    "Cristo Statue",
    "Cathedral Spire",
    "Candelaria Dome",
    "Carioca Mill",
    "Santa Lodge",
    "Bondinho Pylon",
    "Farol Light",
    "Rio Wheel",
    "Niteroi Tower",
    "Palace Deco",
    "Copper Copacabana",
    "Sambadrome Drum",
    "Sugarloaf Cone",
    "Cristo Redentor",
    "Theatro Portico",
    "Favela Ziggurat Court",
  ],
  RIO_PAL,
  [64, 40, 28, 86, 48, 70, 74, 96, 42, 55, 36, 18, 38, 32, 88, 72, 50, 24, 26, 78, 46, 58, 66, 52, 44, 40, 80, 92, 36, 34],
);

export const CIRCUIT_LANDMARKS: Record<string, CircuitLandmarkDef[]> = {
  "westminster-sprint": WESTMINSTER,
  "embankment-run": EMBANKMENT,
  "canary-wharf-loop": CANARY,
  "egypt-pyramids": EGYPT,
  "dubai-marina-circuit": DUBAI,
  "new-york-harbor-circuit": NYC,
  "tokyo-drift-circuit": TOKYO,
  "alps-mountain-pass": ALPS,
  "rio-coast-circuit": RIO,
};

const BY_NAME = new Map<string, CircuitLandmarkDef>();
for (const list of Object.values(CIRCUIT_LANDMARKS)) {
  for (const item of list) BY_NAME.set(item.name.toLowerCase(), item);
}

export function circuitLandmarksFor(slug: string): CircuitLandmarkDef[] {
  return CIRCUIT_LANDMARKS[slug] ?? [];
}

export function circuitLandmarkByName(name?: string): CircuitLandmarkDef | null {
  if (!name) return null;
  return BY_NAME.get(name.toLowerCase()) ?? null;
}
