# bootstrap: writes da_landmark_unique.py
from pathlib import Path
lines = []
def L(s=""):
    lines.append(s)
L('"""Every landmark is unique — name-specific heroes + hashed variation."""')
L("from __future__ import annotations")
L("import hashlib")
L("import math")
L("import unreal")
L("from da_rot import yaw_rot")
L("")
L("def _cube():")
L("    return unreal.EditorAssetLibrary.load_asset('/Engine/BasicShapes/Cube')")
L("def _cyl():")
L("    return unreal.EditorAssetLibrary.load_asset('/Engine/BasicShapes/Cylinder')")
L("def _cone():")
L("    return unreal.EditorAssetLibrary.load_asset('/Engine/BasicShapes/Cone')")
L("def _sphere():")
L("    return unreal.EditorAssetLibrary.load_asset('/Engine/BasicShapes/Sphere')")
L("def _hash(name):")
L("    return int(hashlib.md5(name.encode('utf-8')).hexdigest()[:8], 16)")
L("def _up():")
L("    return yaw_rot(0)")
L("")
L("class Spawner:")
L("    def __init__(self, spawn_fn, tag, folder='DriveAnywhere/Unique'):")
L("        self.spawn = spawn_fn; self.tag = tag; self.folder = folder")
L("        self.mesh = _cube(); self.cyl = _cyl() or self.mesh")
L("        self.cone = _cone() or self.mesh; self.sphere = _sphere() or self.mesh; self.n = 0")
L("    def box(self, loc, sx, sy, sz, mat, col=False, yaw=0):")
L("        self.n += 1")
L("        self.spawn('{}_P{}'.format(self.tag, self.n), self.mesh, loc, unreal.Vector(sx, sy, sz), yaw_rot(yaw), mat, col, self.folder)")
L("    def cyli(self, loc, r, sz, mat, col=False):")
L("        self.n += 1")
L("        self.spawn('{}_C{}'.format(self.tag, self.n), self.cyl, loc, unreal.Vector(r, r, sz), _up(), mat, col, self.folder)")
L("    def coni(self, loc, r, sz, mat, col=False):")
L("        self.n += 1")
L("        self.spawn('{}_N{}'.format(self.tag, self.n), self.cone, loc, unreal.Vector(r, r, sz), _up(), mat, col, self.folder)")
L("    def sph(self, loc, r, mat, col=False):")
L("        self.n += 1")
L("        self.spawn('{}_S{}'.format(self.tag, self.n), self.sphere, loc, unreal.Vector(r, r, r), _up(), mat, col, self.folder)")
L("")
# Append hero builders + build_landmark via second file load
Path('_gen_unique_part1.py').write_text('\n'.join(lines)+'\n', encoding='utf-8')
print('part1', len(lines))
